### PR TITLE
Bump foodcritic dependency from 9.*.* to 10.*.*

### PR DESCRIPTION
**Pull request by jeroenj**

### CODE REVIEW

**Comment by mmozuras** [comment]
@jeroenj I ran it with `10.*.*` on Vinted's chef repo. It did not detect any issues. It detects a few with `9.*.*`. Were those detections deprecated?

**Comment by jeroenj** [comment]
Which offences did it detect on `9.x` that it did not detect on `10.x`? Some rules have been deprecated/removed (e.g. FC023 which wasn't uncommon to happen because it wasn't alsways fixable).

We've been using [it](https://github.com/openminds/pronto-foodcritic/tree/openminds-0.8.1) in our repo for the past few days and it detects quite some offences.

**Comment by mmozuras** [comment]
@jeroenj thanks, those rules being removed explains it!

**Comment by mmozuras** [comment]
Released as [v0.8.2](https://github.com/mmozuras/pronto-foodcritic/releases/tag/v0.8.2).

**Comment by jeroenj** [comment]
Great. 👌 Thanks :)

**Pull request merged**
